version: '3'
services: 
  mysql:
    build: ./mysql
#    args:
#      - MYSQL_VERSION=${}MYSQL_VERSION}
    environment:
      # - MYSQL_DATABASE=${MYSQL_DATABASE}
      # - MYSQL_USER=${MYSQL_USER}
      # - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      # - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      # - TZ=${WORKSPACE_TIMEZONE}
      - MYSQL_DATABASE=testing
      - MYSQL_USER=sadmin
      - MYSQL_PASSWORD=Aa123456
      - MYSQL_ROOT_PASSWORD=Aa123456
      - TZ=UTC
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      # - "${MYSQL_PORT}:3306"
      - "3306:3306"
    networks:
      - backend

  phpmyadmin:
      build: ./phpmyadmin
      environment:
        # - PMA_ARBITRARY=1
        # - MYSQL_USER=${PMA_USER}
        # - MYSQL_PASSWORD=${PMA_PASSWORD}
        # - MYSQL_ROOT_PASSWORD=${PMA_ROOT_PASSWORD}
        # - MAX_EXECUTION_TIME=${PMA_MAX_EXECUTION_TIME}
        # - MEMORY_LIMIT=${PMA_MEMORY_LIMIT}
        # - UPLOAD_LIMIT=${PMA_UPLOAD_LIMIT}

        - PMA_ARBITRARY=1
        - MYSQL_USER=sadmin
        - MYSQL_PASSWORD=Aa123456
        - MYSQL_ROOT_PASSWORD=Aa123456
        - MAX_EXECUTION_TIME=600
        - MEMORY_LIMIT=256M
        - UPLOAD_LIMIT=2G
      ports:
        # - "${PMA_PORT}:80"
        - "8081:80"
      # depends_on:
      #   - "${PMA_DB_ENGINE}"
      networks:
        - frontend
        - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge