version: '3'
services: 
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/public:/public
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf
    # build:
      # context: ./nginx
#       args:
#         # - CHANGE_SOURCE=${CHANGE_SOURCE}
#         # - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
#         # - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
#         # - http_proxy
#         # - https_proxy
#         # - no_proxy
#         - CHANGE_SOURCE=false
#         - PHP_UPSTREAM_CONTAINER=php-fpm
#         - PHP_UPSTREAM_PORT=9000
#         - http_proxy
#         - https_proxy
#         - no_proxy
#     volumes:
# #      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
# #      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
# #      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
# #      - ${NGINX_SSL_PATH}:/etc/nginx/ssl
#       - ../:/var/www:cached
#       - ./logs/nginx:/var/log/nginx
#       - ./nginx/sites:/etc/nginx/sites-available

#     ports:
#       # - "${NGINX_HOST_HTTP_PORT}:80"
#       # - "${NGINX_HOST_HTTPS_PORT}:443"
#       # - "${VARNISH_BACKEND_PORT}:81"
#       - "80:80"
#       - "443:443"
#     # depends_on:
#     #   - php-fpm
#     networks:
#         - frontend
#         - backend


  mysql:
    build: ./mysql
#    args:
#      - MYSQL_VERSION=${}MYSQL_VERSION}
    environment:
      # - MYSQL_DATABASE=${MYSQL_DATABASE}
      # - MYSQL_USER=${MYSQL_USER}
      # - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      # - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      # - TZ=${WORKSPACE_TIMEZONE}
      - MYSQL_DATABASE=testing
      - MYSQL_USER=sadmin
      - MYSQL_PASSWORD=Aa123456
      - MYSQL_ROOT_PASSWORD=Aa123456
      - TZ=UTC
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      # - "${MYSQL_PORT}:3306"
      - "3306:3306"
    networks:
      - backend

  phpmyadmin:
      build: ./phpmyadmin
      environment:
        # - PMA_ARBITRARY=1
        # - MYSQL_USER=${PMA_USER}
        # - MYSQL_PASSWORD=${PMA_PASSWORD}
        # - MYSQL_ROOT_PASSWORD=${PMA_ROOT_PASSWORD}
        # - MAX_EXECUTION_TIME=${PMA_MAX_EXECUTION_TIME}
        # - MEMORY_LIMIT=${PMA_MEMORY_LIMIT}
        # - UPLOAD_LIMIT=${PMA_UPLOAD_LIMIT}
        - PMA_HOST=mysql
        - PMA_ARBITRARY=1
        - MYSQL_USER=sadmin
        - MYSQL_PASSWORD=Aa123456
        - MYSQL_ROOT_PASSWORD=Aa123456
        - MAX_EXECUTION_TIME=600
        - MEMORY_LIMIT=256M
        - UPLOAD_LIMIT=2G
      ports:
        # - "${PMA_PORT}:80"
        - "8081:80"
      # depends_on:
      #   - "${PMA_DB_ENGINE}"
      links:
        - mysql
      networks:
        - frontend
        - backend

volumes:
  dbdata:

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge